Validate alex version in generate-lexer

diff --git a/tools/generate-lexer b/tools/generate-lexer
--- a/tools/generate-lexer
+++ b/tools/generate-lexer
@@ -5,6 +5,11 @@ set -e
 # Start in project root
 cd $(dirname "$0")/..
 
+if ! alex --version | grep '^Alex version 3.2.3,' >/dev/null; then
+  >&2 echo "alex version 3.2.3 is required"
+  exit 1
+fi
+
 source tools/common.bash
 
 # Generate lexer
